;;;; problem_two.lisp
;;;; Project Euler
;;;; Problem 2 - Even Fibonacci numbers	
;;;;
;;;; Each new term of the Fibonacci sequence is generated by adding the previous
;;;; two terms. By starting with 1 and 2, the first 10 terms will be:
;;;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;;;
;;;; By considering the terms in the Fibonacci sequence whose values do not
;;;; exceed four million, find the sum of the even-valued terms.
;;;;
(in-package #:project-euler)

(defun problem-two (limit) (even-sum-fibonacci limit))